# Generated by Django 2.2.8 on 2019-12-29 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(choices=[('Womens Red-Tshirt', 'Womens Red-Tshirt'), ('Womens Pink-Tshirt', 'Womens Pink-Tshirt'), ('Womens White-Tshirt', 'Womens White-Tshirt'), ('Mens Black-Tshirt', 'Mens Black-Tshirt'), ('Mens White-Tshirt', 'Mens White-Tshirt'), ('Mens Striped-Tshirt', 'Mens Striped-Tshirt'), ('Boy Tshirt', 'Boy Tshirt'), ('Girl Unicorn-Tshirt', 'Girl Unicorn-Tshirt')], max_length=100)),
                ('user_feedback', models.TextField(null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ratings', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
