# Generated by Django 2.2.8 on 2019-12-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20191229_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='product_name',
            field=models.CharField(choices=[('Womens Red-Tshirt', 'Womens Red-Tshirt'), ('Womens Pink-Tshirt', 'Womens Pink-Tshirt'), ('Womens White-Tshirt', 'Womens White-Tshirt'), ('Mens Black-Tshirt', 'Mens Black-Tshirt'), ('Mens Black- Skeleton-Tshirt', 'Mens Black-Skeleton-Tshirt'), ('Mens White-Tshirt', 'Mens White-Tshirt'), ('Mens Striped-Tshirt', 'Mens Striped-Tshirt'), ('Boy White-Tshirt', 'Boy White-Tshirt'), ('Boy Striped-Tshirt', 'Boy Striped-Tshirt'), ('Girl Pink-Unicorn-Tshirt', 'Girl Pink-Unicorn-Tshirt')], max_length=100),
        ),
    ]
