# Generated by Django 2.2.8 on 2019-12-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='created_date',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='star_ratings.Rating'),
        ),
    ]
