# Generated by Django 2.2.8 on 2019-12-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20191229_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
