# Generated by Django 2.2.8 on 2019-12-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedback_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ratings',
            field=models.IntegerField(verbose_name='star_ratings.Rating'),
        ),
    ]
