# Generated by Django 2.2.8 on 2020-01-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20191229_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='product_name',
            field=models.CharField(choices=[('Womens Red-Tshirt', 'Womens Red-Tshirt'), ('Womens Pink-Tshirt', 'Womens Pink-Tshirt'), ('Womens White-Tshirt', 'Womens White-Tshirt'), ('Mens Black-Tshirt', 'Mens Black-Tshirt'), ('Mens Black- Skeleton-Tshirt', 'Mens Black-Skeleton-Tshirt'), ('Mens White-Tshirt', 'Mens White-Tshirt'), ('Mens Striped-Tshirt', 'Mens Striped-Tshirt'), ('Boy White-Tshirt', 'Boy White-Tshirt'), ('Boy Striped-Tshirt', 'Boy Striped-Tshirt'), ('Girl Pink-Unicorn-Tshirt', 'Girl Pink-Unicorn-Tshirt')], default='Please choose', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ratings',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Please choose', max_length=100),
        ),
    ]
