# Generated by Django 2.2.8 on 2019-12-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Black', 'Black'), ('White', 'White')], max_length=1)),
            ],
        ),
    ]
