# Generated by Django 2.2.8 on 2019-12-27 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Girl', 'Girl'), ('Boy', 'Boy')])),
                ('product_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
