# Generated by Django 2.2.8 on 2019-12-21 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Black', 'Black'), ('White', 'White')], default=datetime.datetime(2019, 12, 21, 8, 56, 53, 17517, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XLarge')], max_length=1),
        ),
    ]
