# Generated by Django 2.2.8 on 2019-12-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191221_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Girl', 'Girl'), ('Boy', 'Boy')], max_length=1),
        ),
    ]
