# Generated by Django 2.2.8 on 2019-12-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191221_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Girl', 'Girl'), ('Boy', 'Boy')]),
        ),
    ]
