# Generated by Django 2.2.8 on 2019-12-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(choices=[('SMALL', 'SMALL'), ('LARGE', 'LARGE'), ('MEDIUM', 'MEDIUM'), ('XLARGE', 'XLARGE')], default='SMALL'),
        ),
    ]
