# Generated by Django 2.2.8 on 2019-12-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
