# Generated by Django 2.2.8 on 2019-12-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_date',
        ),
    ]
