# Generated by Django 2.2.8 on 2019-12-26 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
